# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-12-10 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20170206_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='owner',
        ),
    ]
